### ISSUE TITLE
Is there a way to use the bot behind a proxy?

### ISSUE THREAD

**Issue by samthelion17** [Corsinvest/cv4pve-botgram#2]
If not, please add proxy support.

Cheers!

**Comment by franklupo** [comment]
Hi,
proxy for connecting to telegram?

**Comment by samthelion17** [comment]
> 
> 
> Hi,
> proxy for connecting to telegram?

Yes, i'm behind a corp.  proxy, so the bot needs to be able to connect to the telegram API through that proxy.

**Comment by samthelion17** [comment]
I've tested the bot today and it works as expected when the environment variables _http_proxy_ and _https_proxy_ are set correctly. My tests were performed on an Ubuntu 20.04 OS. I'm sorry for opening an issue without testing first.

Best Regards!
