### ISSUE TITLE
password for bot or specify chat id

### ISSUE THREAD

**Issue by meccli** [Corsinvest/cv4pve-botgram#3]
Hi, have you any options to make the chat with the bot not open worldwide? I can't find them in the instructions

**Comment by franklupo** [comment]
See official documentation bot cration

**Comment by meccli** [comment]
Do you mean privacy mode?

**Comment by franklupo** [comment]
Hi,
in BotFather it is possible to specify settings on groups. You can specify the problem better.

Best greards

**Comment by meccli** [comment]
I am saying if the bot is working, any user can find my bot in the global search and can stop and start my machines. is there any kind of protection to that? maybe specifying the user id who can run commands or a password

Thank you

**Comment by franklupo** [comment]
HI,

I thought that a solution would be to create a parameter with valid ChatId
example
`--chatsId` "XXXXX, YYYY, ZZZZZ '"

if not specified the chat is open

Do you think?

**Comment by samthelion17** [comment]
Or you could even create a config file to store all the parameters that the bot needs to work properly, instead of passing it via command line arguments... even more store the password in an encrypted form!

**Comment by franklupo** [comment]
the password can be saved in file in the form
--password: path_file
The first time he will ask for the password and save it in the file. The subsequent executions slight the password from the encrypted file.

  a new option is under study --config where to specify the file with all the options

best regards

**Comment by franklupo** [comment]
no longer interested?

**Comment by franklupo** [comment]
Hi @meccli 
Have you found any way to limit access?

**Comment by samthelion17** [comment]
good thing you reopened this, 'cause i'm interested.

**Comment by franklupo** [comment]
> HI,
> 
> I thought that a solution would be to create a parameter with valid ChatId
> example
> `--chatsId` "XXXXX, YYYY, ZZZZZ '"
> 
> if not specified the chat is open
> 
> Do you think?

What do you think?
