### ISSUE TITLE
Bot token invalid format exception

### ISSUE THREAD

**Issue by SpaceMaster85** [Corsinvest/cv4pve-botgram#5]
Hi,
thank you for your work. Unfortunately it is not working for me.
New created bot tokens throw a invalid format exception.

![image](https://user-images.githubusercontent.com/19744998/180958195-f60051a7-0e86-433b-9d71-e6014a5ec2af.png)

![image](https://user-images.githubusercontent.com/19744998/180958439-60f7ab5c-8c22-4fb8-8b78-701ab8eb1256.png)

I tried it with several tokens but always with the same result.

I assume it has something to do with the ID exceeding the INT range. A token with shorter ID from an older bot is working fine.

Maybe it is related with this issue
https://github.com/openhab/openhab-addons/issues/11732

Steps to reproduce:

1. Generate new bot
2. Copy token
3. Start program with new token
4. Exception

**Comment by franklupo** [comment]
Hi,
checked the problem

best regards

**Comment by dszubov** [comment]
i also observed this error while deploying bot
<img width="1080" alt="Снимок экрана 2022-09-06 в 16 41 42" src="https://user-images.githubusercontent.com/104792259/188638128-49fd9022-2abc-4ce4-97ed-2438f627c380.png">

**Comment by franklupo** [comment]
New release 
https://github.com/Corsinvest/cv4pve-botgram/releases/tag/v1.5.2

Best regards
