### ISSUE TITLE
restoring lxc/vm by one command?

### ISSUE THREAD

**Issue by dszubov** [Corsinvest/cv4pve-botgram#8]
Is it possible to make command to restore lxc/vm from last backup? for example script can parse all backups by date and pick fresher for restore
i've make backup schedule for entire all pve in some cases need to restore my lxc/vm where i can't to ssh/http.

**Comment by franklupo** [comment]
Hi,

download last version, run command.
If you can create an alias command remove foirst "/" backslash

```
list backup vm in specific storage
/get /nodes/{node}/storage/{storage}/content vmid:{vmid} content:backup

restore qemu
/create /nodes/{node}/qemu vmid:{vmid} force:0 storage:{storage} ostemplate:{volid} restore:1

restore lxc
/create /nodes/{node}/lxc vmid:{vmid} force:0 archive:{volid}
```

For commercial support or custom request please contact

**Comment by franklupo** [comment]
News?
